name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Run Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install gtest
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
    - name: install valgrind
      run: sudo apt-get install valgrind
    - name: build tests
      run: make allTests
    - name: run tests
      run: ./test_fileTransfer
    - name: clean up
      run: make clean
